name: gina
description: "A new Flutter project."
publish_to: "none"
# IOS Version
version: 1.4.0+7
#Android Version
#version: 1.0.7+13


environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^6.3.0
  dartz: ^0.10.1
  dio: ^5.9.2
  feather_icons: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  firebase_database: ^12.3.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  font_awesome_flutter: ^10.9.1
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  lottie: ^3.3.1
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.5+1
  google_maps_flutter: ^2.14.0
  google_maps_flutter_android: ^2.18.3
  geolocator: ^14.0.2
  http: ^1.6.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  flutter_polyline_points: ^3.1.0
  geocoding: ^4.0.0
  firebase_storage: ^13.4.1
  #flutter_webrtc: ^1.4.1
  livekit_client: ^2.5.7
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.5.0
  connectivity_plus: ^7.3.1
  internet_connection_checker_plus: ^3.1.1
  device_info_plus: ^12.4.0
  firebase_messaging: ^16.4.3
  app_links: ^7.0.0
  package_info_plus: ^9.0.1

  path_provider: ^2.1.5

  avatar_glow: ^3.0.1
  audioplayers: ^6.6.0

# flutter_background_service_android:
#   path: packages/flutter_background_service_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png" # Android
  # Ou cor sólida:
  adaptive_icon_background: "#FF5000"

  # Configurações iOS
  remove_alpha_ios: true # Remove transparência no iOS

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/
