// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1-IvnBHuZEZ0AsKsXBg0LINIztswTeD8',
    appId: '1:926124252420:web:a21e246699dfed80cb8451',
    messagingSenderId: '926124252420',
    projectId: 'basta-82cce',
    authDomain: 'basta-82cce.firebaseapp.com',
    storageBucket: 'basta-82cce.firebasestorage.app',
    measurementId: 'G-94VXZEXMC9',
    databaseURL: 'https://basta-82cce-default-rtdb.firebaseio.com',
    

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqhXUrz-ayCMgZMkxVBOVAfH_aT0_kqQ',
    appId: '1:926124252420:android:5d22557189586fd4cb8451',
    messagingSenderId: '926124252420',
    projectId: 'basta-82cce',
    storageBucket: 'basta-82cce.firebasestorage.app',
    databaseURL: 'https://basta-82cce-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO2hOkROec5JSZyGtrd5lxZEMKxYmgMGA',
    appId: '1:926124252420:ios:9ade28edbbe6078bcb8451',
    messagingSenderId: '926124252420',
    projectId: 'basta-82cce',
    storageBucket: 'basta-82cce.firebasestorage.app',
    iosBundleId: 'com.example.gina',
    databaseURL: 'https://basta-82cce-default-rtdb.firebaseio.com',
  );
}
