# Uncomment this line to define a global platform for your project
platform :ios, '18.0'

# FORÇAR UNIFICAÇÃO DO WEBRTC-SDK (Resolve o conflito de versões)
pre_install do |installer|
  Pod::Specification.class_eval do
    alias_method :old_dependency, :dependency
    def dependency(*args)
      # Se qualquer plugin pedir o WebRTC-SDK (seja o LiveKit ou o Flutter WebRTC), forçamos a 137.7151.03
      if args[0] == 'WebRTC-SDK'
        args[1] = '137.7151.03'
      end
      old_dependency(*args)
    end
  end
end

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
# ADICIONE ESTE BLOCO PARA O SEU WIDGET:
target 'EmergencyWidgetExtension' do
  use_frameworks!
  use_modular_headers!
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Garante compatibilidade do iOS Deployment Target com o LiveKit
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
      
      # Necessário para compatibilidade com Apple Silicon (M1/M2 do seu Mac mini)
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end